# Generated by Django 2.2.13 on 2020-12-04 12:47
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('model_type', models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('Speech2text', 'speech to text')], max_length=30)),
                ('config_file', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('model_type', models.CharField(choices=[('DocumentClassification', 'document classification'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('Speech2text', 'speech to text')], max_length=30)),
                ('predict_labels', django_postgres_extensions.models.fields.JSONField()),
                ('backend_parameters', django_postgres_extensions.models.fields.JSONField(blank=True, null=True)),
                ('model_version', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_backend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_projects', to='api.ModelBackend')),
                ('target_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_projects', to='api.Project')),
            ],
        ),
    ]
